In [28]:
import pandas as pd
import yfinance as yf

In [29]:
NASDAQ = pd.read_csv("../data/Stock_info/NASDAQ.csv")
NASDAQ.sort_values(by=["Market Cap"], ascending=False, inplace=True)
NASDAQ_symbols = NASDAQ[(NASDAQ["IPO Year"]<2009).values & (NASDAQ["IPO Year"].notna()).values & (NASDAQ["Name"].str.contains("Common Stock").values)][0:100]["Symbol"].values

In [31]:
NASDAQ_stock = yf.download(NASDAQ_symbols.tolist(), start="2009-01-02", end="2022-01-01")

[*********************100%***********************]  100 of 100 completed

In [32]:
NASDAQ_stock

             Adj Close                                                 \
                  AAPL        ADBE       AGNC        AKAM        ALGN
Date
2009-01-02    2.775246   23.020000   3.303952   15.740000    8.890000
2009-01-05    2.892371   23.129999   3.329195   16.180000    9.250000
2009-01-06    2.844666   24.219999   3.343398   16.450001    9.600000
2009-01-07    2.783196   24.230000   3.333930   15.470000    9.360000
2009-01-08    2.834879   24.290001   3.351286   15.510000    9.010000
...                ...         ...        ...         ...         ...
2021-12-27  180.100540  577.679993  15.225006  117.919998  661.070007
2021-12-28  179.061859  569.359985  15.244689  118.449997  656.369995
2021-12-29  179.151749  569.289978  15.146274  118.330002  653.340027
2021-12-30  177.973251  570.530029  15.086759  117.150002  662.219971
2021-12-31  177.344055  567.059998  14.918136  117.040001  657.179993

                                                                         ...  \
                  ALNY        AMAT        AMGN         AMZN        ANSS  ...
Date                                                                     ...
2009-01-02   25.150000    8.359757   45.615871    54.360001   28.740000  ...
2009-01-05   25.440001    8.359757   46.126244    54.060001   28.809999  ...
2009-01-06   25.940001    9.072725   45.113243    57.360001   29.080000  ...
2009-01-07   24.320000    8.304914   45.004971    56.200001   27.540001  ...
2009-01-08   24.000000    8.414601   45.824650    57.160000   26.480000  ...
...                ...         ...         ...          ...         ...  ...
2021-12-27  161.110001  162.720001  225.169998  3393.389893  411.220001  ...
2021-12-28  168.699997  159.639999  225.770004  3413.219971  409.920013  ...
2021-12-29  170.080002  160.979996  227.600006  3384.020020  407.059998  ...
2021-12-30  171.029999  157.979996  226.470001  3372.889893  405.679993  ...
2021-12-31  169.580002  157.360001  224.970001  3334.340088  401.119995  ...

             Volume                                                       \
               TSCO    TTEK     TTWO     ULTA     UTHR     VRSN     VRTX
Date
2009-01-02  3110000  466500   845000   333600   859600  3222500  1216600
2009-01-05  5456400  686800  1223400   299400   695600  2708800  2331600
2009-01-06  4319200  632500  1629600   187000  1109400  4158500  2055600
2009-01-07  6407200  442200   847600   157900   871400  3259000  1703300
2009-01-08  4115600  564700  1249600  1648800   773800  3054100  1867600
...             ...     ...      ...      ...      ...      ...      ...
2021-12-27   381500  270500   582500   648200   264800   291500  2073400
2021-12-28   343400  387600   600800   402100   172500   372400  1066900
2021-12-29   525000  171300   514900   338900   225800   325900   726200
2021-12-30   361800  188500   665000   406500   302700   223500   961500
2021-12-31   307500  252600   858700   445400   192200   345500  1142000


                XLNX     XRAY    ZBRA
Date
2009-01-02   6026000  1574200  559600
2009-01-05   5936600  1484200  383100
2009-01-06   6199300  2324700  298500
2009-01-07   6296000  2345400  356900
2009-01-08  14456300  1875600  511100
...              ...      ...     ...
2021-12-27   2911900  1268500  636400
2021-12-28   2844800   772100  139500
2021-12-29   2413800  1112400  128600
2021-12-30   1513800  1119100   87500
2021-12-31   2538300   578900  117100

[3273 rows x 600 columns]

In [39]:
NASDAQ_stock.reset_index().to_csv("../data/Stock_data/NASDAQ.csv", index=False)